### ISSUE TITLE
Replace the `async` module with Brackets' async implementation

### ISSUE THREAD

**Issue by gideonthomas** [humphd/brackets-browser-livedev#2]

**Comment by humphd** [comment]
Mentioned IRL, but putting here too.  One idea here would be to write a wrapper around the Brackets Async method calls in order to transform them into async.js style callback calls.  If you did this, it would involve fewer code changes overall.  Either way works, though.

**Comment by gideonthomas** [comment]
Fixed with d8363dc39a3f28f60bceb1cd741b0a96ce770417
