### ISSUE TITLE
Fix indenting

### ISSUE THREAD

**Issue by puzzledShark** [humphd/brackets-browser-livedev#66]
Nearly all of brackets live-dev is indented with 4 spaces rather than 2 spaces

Edit: Mistake, not true

**Comment by humphd** [comment]
It should be 4-spaces, since we want to include this in the `brackets/src/extensions/default` soon, and all of Brackets is 4-space indent.

**Comment by humphd** [comment]
Instead of changing to 2-spaces, can you make this about changing it all to 4?
